# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d141ea50f3d923c338279249491177f16d3ac7c0f5d606d0832182e39ba32cd285e454a5bac76dd45da48deab62e28352ead5b9255eb2500df87fb7a53ae8b35

test:
  secret_key_base: e5f3709613444cc6e178db58bff59624e8acb9a8dbe2c0a68b0a838b4c2bc836e56f4d67babc6d97cd4d19e4ece63961dac23d5e24f8a258c1de551cbecd65f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
